version: '3.8'

services:
  frontend:
    image: kartikringola/frontend-course:latest  # Use the image from Docker Hub
    ports:
      - "3000:80"  # The website is running in port 3000 of your local host, just simply type http://localhost:3000 to view the website
    depends_on:
      - backend  # Ensure backend is started before frontend

  backend:
    image: kartikringola/backend-course:latest  # Use the image from Docker Hub
    ports:
      - "8080:8080"  # Map port 8080 in the container to port 8080 on your host
    


